services:
  redis:
    image: redis:7-alpine
    container_name: logminer-redis
    ports:
      - "6379:6379"
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--appendfsync",
        "everysec",
        "--maxmemory",
        "512mb",
        "--maxmemory-policy",
        "noeviction"
      ]
    volumes:
      - logminer_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  logminer_redis_data:
